README.md
=> Improvements to README.MD

app/src/main/res/values-it/strings.xml
Added intalian translation on project.
=> Add strings.xml

PLAY-zh-rCN.md, app/src/main/res/values-zh-rCN/strings.xml
Along with a minor update in strings.xml
=> Play store description in Simplified Chinese

app/src/main/res/values-ro/strings.xml
The line split was on purpuse?
=> Updated Romanian translation

PLAY.md
Added the **Vpn**Service API mention just to be clear on HOW it works, since a sudden VPN dialog appearing out of the blue is no fun.
=> Updated PlayStore description

app/src/main/res/values-it/strings.xml
Sorry, I've noticed and fixed a typo in the translation.
=> Fixing typo in italian strings

README.md
...and a tip about the use of _device in use_ mode
=> Added FAQ#8 about PlayStore

README.md
Improved clarity, ensured consistency, fixed errors, corrected grammar, split run-on sentences.
=> More enhancements

app/src/main/res/values/strings.xml
=> Improved strings

PLAY.md
The "most of these features" paragraph was separated from the list of features, making it awkward.  I reorganized things a bit to make it easier to read and understand.
=> Enhancements

README.md
Grouped they are more readable
=> Update order of optionals

PLAY.md
Grouped they are more readable
=> Update order of optionals in description

PLAY-ro.md
=> Update Romanian description

app/src/main/res/values-ro/strings.xml
=> Update Romanian translation

app/src/main/res/values-de/strings.xml
Fixed typo in German translation
=> Fixed typo

README.md
FAQ#13
A5 5.0.2 does the first
Xperia 5.1.1 does the second
FAQ#14
=> Expanded FAQ#13 and added FAQ#14

app/src/main/res/values-ro/strings.xml
It pays to delete data on a new version. ;)
=> Minor fix in Romanian

README.md
=> Sorted devices

README.md
Hope the Github/F-Droid/XDA logo sources don't break anything.
=> Add nice logos for downloads

README.md
Reverts M66B/NetGuard#156
I think it is ugly, sorry.
=> Revert "Add nice logos for downloads"

FAQ.md, README.md
Removed that part about the Store, it was wrong ( device in use =/= app in use ).
There is no notification icon in the status bar on low priority notifications, only on high, right?
s/store/Store/g
=> Some fixes in FAQ

app/src/main/java/eu/faircode/netguard/Util.java
=> Revert "Workaround for devices with 3G/LTE returning false when calling hasSy…"

README.md
Fix https://github.com/M66B/NetGuard/issues/189 (again) since F-Droid started to build it again https://gitlab.com/fdroid/fdroiddata/issues/358
=> Re-add F-Droid builds link

FAQ.md, README.md
Thanks very much for the app. It works on a Samsung Galaxy S5 (except the [known problem](https://github.com/M66B/NetGuard/issues/223)) on Stock Android from Samsung 5.0.2.
=> Fixed spelling and hyperlink target.

app/src/main/java/eu/faircode/netguard/ActivityMain.java
Fixes M66B/NetGuard/issues/232
=> keep search while refreshing the list;

app/src/main/java/eu/faircode/netguard/ActivityLog.java, app/src/main/java/eu/faircode/netguard/DatabaseHelper.java, app/src/main/res/menu/log.xml
=> filter log by ip

FAQ.md
I said *current* since host blocking is not an official feature yet ;)
=> Update FAQ with info on AFWall+

README.md
The README.md already mentions it anyway...
=> Link the ad block guide

FAQ.md
Hope you are doing well Marcel.  BTW, I sent you an email...
=> Many enhancements to FAQ

FAQ.md
=> Further enhancements to the FAQ

FAQ.md
=> Reworked FAQ #0

ADBLOCKING.md
Thank you for pointing me to this file.
=> Multiple Enhancements

ADBLOCKING.md
Let me know if I got it all right.
=> Added info regarding duplicate entries in hosts

ADBLOCKING.md, FAQ.md
Please fact-check my addition to Q#28.
=> Further improvements

app/src/main/jni/netguard/netguard.c, app/src/main/jni/netguard/netguard.h
=> Bug fix for sdk initializer.

tools/crowdin.sh
To the degree I understood your comments on #515, and Linux command line syntaxes, I've now instead attempted to tie values-no to values-nb, on the presumption that it'll make the Norwegian Crowdin translation project apply to both of those files.
=> Attempting to redirect 'no' to 'nb'
